source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '12.0'

target 'WeatherSample' do
  use_frameworks!
  pod 'Applanga'
end

target 'WeatherSampleUITests' do
  use_frameworks!
  pod 'ApplangaUITest'
end
