name: weather_sample
description: This is a sample application to showcase the possible usage of applanga_flutter.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter  


  applanga_flutter: ^3.0.44

  http: ^0.13.4
  intl: ^0.17.0
  webview_flutter: ^3.0.1
  shared_preferences: ^2.0.13
  flutter_inappwebview: ^5.3.2

dev_dependencies:

  json_serializable: ^6.1.5
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter:

  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/about_page.css
    - assets/about_page.html

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

applanga_flutter:
  update_languages: [en, de, fr]
  access_token: xxxxxxxxxxxxxxxx