# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ApplangaWeather' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Applanga'
  pod 'Alamofire', '~> 5.2'
  # Pods for ApplangaWeather

  target 'ApplangaWeatherUITests' do
    # Pods for testing
  end

end
